### ISSUE TITLE
Prime Number program is a bit wrong!

### ISSUE THREAD

**Issue by Biprodeep** [fellchase/libpython#5]
One is neither a prime nor a composite number. A prime number is one 
with exactly two positive divisors, itself and one. One has only one 
positive divisor. It cannot be written as a product of two factors, 
neither of which is itself, so one is also not composite. It falls 
in a class of numbers called units. These are the numbers whose 
reciprocals are also whole numbers.

**Comment by fellchase** [comment]
Thanks for reporting bipro. I'll fix it soon

**Comment by fellchase** [comment]
Looks like its fixed now! I also fixed the problem with negative integers

**Comment by 0xcrypto** [comment]
Resolved in #6

**Comment by fellchase** [comment]
Thanks for involvement. I really appreciate it
